language: node_js
node_js:
  - 10.4.0
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
before_deploy:
  - yarn global add firebase-tools
  - yarn run build
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: develop
  token:
    secure: "PnBvJosyjahIIsgR96ZFHbePreGye4krIDUufuyUdTRjda7qJLcyW+UP3ke1YesMfm+xiRZZ7SC8iVflSiuYUsdIYfW7jWggafh8d/7trktCbhshD8pNULb7IUq58b+2Bp0SopTKKU9IyjFAyoXGRttkweIKoam8DkCv0ki0WiNydWuq42cd+OWPt52X0FWDqS5VL9FZh06rnuajcGZ7EhSytNs2PJMaPowwO0g6SwkWLdMvYg8GBuAgHEcOqooebT7nTTNIVmqn+yHmVGXtSTJ4ufPsiqYkiVftW2jDcbOGQ9mtZiADkxZjRuZ8jhhqfgDEa1KLzioz10SuHxewBZLSqY+FEjNFxhyGt6mBDtD9l0Q60gT9cuBlT2nybmX6p283xp00d1pGQt+IFFFh30p9dmx/gGJYKasMGEmvO+Az4ztlDqHnqTHFWqisG87IZFekh40di1uuLnGMTgMpAdgQ0NEGNZEArP4L6CBapYJNX9uhea+iBzjhxxd2lqdNuzuruLbsj09Iu1KbvnpmH7r3rF73SH2iOtwTNT6tHJaBBWSKHMb6KhkfbCJetsIT0cCt7fY6oUMG5pbWrjYv3YT5eb7hx7nLNEHN1UjzTI+f6J40O8xyps3Ub5JsYPm/uCGWwCkvjE1R3krA5isQtoQGQFkh0oUO0hcbW33xaS0="
  project: opent-street-art
