language: node_js
node_js:
  - 10.4.0
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  provider: firebase
  token:
    secure: c/BmGethCCGayHYUvoB/1MRNyTZN8BvUMTrZh3j63C9VfKwibLm8U8nejfRXEmkiuuliX+vEl7rOTQB+fas+Gy0yD7LIb7YLwQQ/4vGF1ZyLv9ize5I8NFvQ3EvnUrUvVKHJdMJG9qsL1GMkxuk27PIwEvcGHslEGsN3JYbVuzTYt9RzwkdZ9zGnhinl3pEJRcrsepBpXcqBbp9QU8GSPC3iifUY4ewYZlnK18fdUg6p3oR28oj7q0/WxX7UVkH64BS6JaUZ+KURTXC1wwJbe1bEiLnaZF1RCr5vPRJFsOWDzbknbC8Phr/EvHx+etPGYf8I5tN3u6qoeJhOGXVBPbTFs+J5NZuGaQERzZvtmdLJT4NiYN4qMdmjWSotFJGlMIBxAL1YrkdKQXMlSvHbh0h+lI7ILwg/mZGu1KVj7yRnBsGza06fEup6jAAgQdHb40ZGLVWses3w44bw5jv802xq+NHDpFD4zoHGJf2dfDtVluipmzgo5jH7VnbhIEhq7KMR3qAZNKSIX1U3pjedflUBrtS8p3akp0/tNsHnfClV8gGFRbwjGVuin2S7DeFwcxU2H0clNBJxHqcws7Rv23PBz/3kd6H/tzlCqTSYpLZMubMDnLIYWOUMLq3tE7C3cAU32Sfm3gE7vX81xYXtST56jqzHbtfFIqTns3z2KaA=
  on:
    branch: develop
