language: node_js
node_js:
  - 10.4.0
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  provider: firebase
  token:
    secure: fj7pIm/jdE79gWbqwUhLi7AokzfNFltmqO+NLr2WC8qUnWZ5wf1ecvEVrEDmQIX8z5FxKjNno3R2rpcT6eqHP+sw7Lb1tEwnoEBmElx83eT70AmpJKy7AKHJT5tGadCbDzamEBD4bgIQQBgH7t2710UzDbxNronBZVk5yEmqw8WwVV+PSi6c0T3bNVh9p0cJ/s7g2Sm7bv2IiJlsGSLaX1ai2J3YMQgCctpMj1Oh1g5T9QBzj8Rg50lw42Bcs4366m3WGdzseY4l53POze9TPA24RWOx/MC5BQ8xkQ0jPqS9Z4d5sazlyo7KK+ac5bO5vrAswx5qjoZThiHgQoAUYk3QLMz9uwSVE3SeIZpE9oJyCxbQUUnCNoxqhO+winuz+qsUtKZZIW1YP4/iaOKRHRpWhHtWzBAsYoTrCaldC5vlBV2/qjkQ8GCOHY5zM9L7/hfgNREJoXALU/VSjYBc/RCHVFPSvL8Ye3KYl4xEL961oB85q2bpY2QLJYl5NPAhEF1XazxMKtobssyGMj0IX8lMzM/y3uPGnd7PQpLnjvVgEvaNQmrn6qSNeOR2kxIcl/Xk0VzL7mdVG+8IcfvVMF0w62zlalmoO7yVIjNUFk+ob3yTcCh+qhp0Hm9KYJp0y7foGZYudHVR5DYhJbBkxmWhPP/AXTc9hufWqZVBUEU=
  on:
    branch: develop
