language: node_js
node_js:
  - 10.4.0
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  provider: firebase
  token:
    secure: "V9+7/xa0wyJ41N31ymcp+a/oyVx2JQZamjo86q98p5+SdnDSwAFIQSNbUui4FM4OvAukXxaGlg0zhomtVoJr8st36IB2c0aNYrk+qQGKoC04OYrxs/25S49IBX32D+vaCS7ldIpGYYw4maWi6kOc4pUwSa6+CKqwqw+sXTVR26IE5Tlred3NQx/Qgzx0zrbBoiW4ueuzhFN5QbfCxYNpc29uigX+vAbOuE3NOEIYzGc13qlz/QluKaYerWBoEwGuAdrIK798pkbFRIeg2xONW8S8vnVBlTxykIsd70+Jc4DZ8H4/bL5a7rFhv8Aa3SIWV+/QNdqFeexRXqE2qP0034RmecIy3MZGco4oZiPc3j8HBR/M8Ufl2iR2MSC88BHE6ub1j1DPYBh1syxRoiwIGi20HFXeDTEIXpirbiji2CtjtuxgD8FGofTvUC7I28TCdYEAI0hNd1q7p+9nwqVXB7seCuhzDstbYZhrBoqEzvoASzGFUPM7VdlsZqsodVCSUEcQXKWwbFNpICXJGvcGcItcfC9WafQOTgC6tuv076CC7vdjLPQs85ZiVh/IJxMGsMuUTv3scrUAo0VP20tSfGy9I/eVjmOrj3FFbHqgXpazm9jaGFdFimj1yFIdD9oIJ5hc4HXfrJVCI3DqHzzZMJU1FQhJ9aKR/7FxtFWW2PM="
  on:
    branch: develop
